### ISSUE TITLE
mem-fs-editor's usage is broken in Pull request #129; passing filename as an array

### ISSUE THREAD

**Issue by denchistyakov** [mde/ejs#166]
Good day,

We find error at `lib/ejs.js:529:68` — property `this.opts.filename` could be Array and in this case we get this trace:
```
TypeError: this.opts.filename.replace is not a function
    at Object.Template.generateSource (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:529:68)
    at Object.Template.compile (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:444:12)
    at Object.compile (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:289:16)
    at handleCache (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:148:16)
    at Object.exports.render (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:316:10)
    at copy.process (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:51:16)
    at EditionInterface.<anonymous> (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:38:10)
    at Array.forEach (native)
```

**Comment by RyanZim** [comment]
@denchistyakov Thanks for reporting! Could you outline the **_exact_ steps** to reproduce this issue? Thanks!

**Comment by denchistyakov** [comment]
Hello Ryan,

Minimal test case:
```js
var ejs = require('ejs');
ejs.compile('<%= name %>', { filename: ['file1', 'file2'] });
```

**Comment by RyanZim** [comment]
@denchistyakov I can see that that would cause an error.

What I can't understand is why you would want to do something like this. Perhaps you could explain your use case.

FWIF, the official API docs explicitly specify that `filename` should be a *string*. http://ryanzim.github.io/ejs-api/global.html#Options

**Comment by TimothyGu** [comment]
There has been a somewhat similar issue filed against Pug: pugjs/pug#2393.

**Comment by denchistyakov** [comment]
If you can see by trace we get this problem from yeoman-generator witch use mem-fs-editor witch use your module )

**Comment by RyanZim** [comment]
OK, I see. I will be opening an issue with mem-fs-editor since we never did claim to support `filename` being an array.

**Comment by denchistyakov** [comment]
I create PR https://github.com/denchistyakov/ejs/pull/1 to fix this problem

**Comment by RyanZim** [comment]
I created https://github.com/SBoudrias/mem-fs-editor/issues/59 so that they can resolve their usage of EJS.

**Comment by RyanZim** [comment]
@denchistyakov I don't see the point of adding special handling for `filename` being an array; as I said earlier:

> We never did claim to support `filename` being an array.

I don't think we are responsible for fixing this; mem-fs-editor needs to have handling to prevent sending an array to EJS.

**Comment by RyanZim** [comment]
Things are moving along well at https://github.com/SBoudrias/mem-fs-editor/issues/59. Hope this is resolved for everyone soon.

**Comment by FredKSchott** [comment]
Hey everyone. This change introduced a major bug into our CLI that caused half of our generators to fail (see https://github.com/Polymer/polymer-cli/issues/206). While it looks like the support for an array of filenames was never explicitly supported, it was relied on by us and others through `mem-fs-editor`.

I know breaking changes to implicit behavior are tricky to pin down in semver, but regardless this introduced a breaking change for us and many others who relied on it. Please keep this in mind in the future when cutting new versions.

**Comment by RyanZim** [comment]
@FredKSchott Sorry about that. We were pushing a hotfix for https://github.com/mde/ejs/issues/164, so it was done in haste. We probably still wouldn't have thought about this change though. I opened issue #168 as a possible help for this kind of thing.

**Comment by FredKSchott** [comment]
@RyanZim no worries, these things happen. And fwiw I think you're right, calling `render()` with a `filename` array is very strange behavior that ejs probably shouldn't be supporting.

**Comment by mde** [comment]
If this has been resolved upstream, let's close this.

**Comment by RyanZim** [comment]
@mde Not yet. See https://github.com/SBoudrias/mem-fs-editor/issues/59 for upstream tracking.

**Comment by mde** [comment]
Or maybe I should have said: if we aren't planning to make changes here, we can close this now as a WONTFIX. Do we need a tag for that?

**Comment by RyanZim** [comment]
@mde No tag needed. I was just leaving it open for the benefit of others affected by this change.

**Comment by RyanZim** [comment]
Fixed upstream; closing. Thanks for reporting.
