### PR TITLE
Fix #166

### LINKED ISSUE #166: mem-fs-editor's usage is broken in Pull request #129; passing filename as an array
Good day,

We find error at `lib/ejs.js:529:68` — property `this.opts.filename` could be Array and in this case we get this trace:
```
TypeError: this.opts.filename.replace is not a function
    at Object.Template.generateSource (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:529:68)
    at Object.Template.compile (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:444:12)
    at Object.compile (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:289:16)
    at handleCache (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:148:16)
    at Object.exports.render (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:316:10)
    at copy.process (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:51:16)
    at EditionInterface.<anonymous> (/home/dench/node_modules/generator-project-stub/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:38:10)
    at Array.forEach (native)
```

### PR DESCRIPTION
**Pull request by denchistyakov**

### CODE REVIEW

**Comment by RyanZim** [comment]
I don't see the point of adding special handling for `filename` being an array;

> We never did claim to support `filename` being an array.

I don't think we are responsible for fixing this; mem-fs-editor needs to have handling to prevent sending an array to EJS.

**Comment by RyanZim** [comment]
mem-fs-editor fixed their usage of EJS. Closing. Thanks anyway.
